### ISSUE TITLE
Requested runtime (Python-3.5) is not available for this stack (heroku-16)

### ISSUE THREAD

**Issue by Hoshitter1** [Hoshitter1/hoshito_bot#1]
Could you tell me how to solve this error?

I'm currently trying to set up an app created by Python on Heroku, and after sending this command on my laptop "git push heroku master", I got this error "Requested runtime (Python-3.5) is not available for this stack (heroku-16)"(Full messages are stated in the bottom).

The files I added to my git repository is 
////
Hoshito_bot.py
index.py (fake web app)
Procfile (that says "worker: python index.py")
requirements.txt (that says the libraries for "Hoshito_bot.py")
runtime.txt  (that says "Python-3.5")
////

The process I followed before "git push heroku master" was
////
cd (directory name that contains the files above) 
heroku login
git add .
git commit -m "make it better"
////

Full massage I got after the command was
////
Counting objects: 33, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (27/27), done.
Writing objects: 100% (33/33), 6.54 KiB | 957.00 KiB/s, done.
Total 33 (delta 10), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Python app detected
remote:  !     The latest version of Python 3 is python-3.6.4 (you are using Python-3.5, which is unsupported).
remote:  !     We recommend upgrading by specifying the latest version (python-3.6.4).
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
remote: -----> Installing Python-3.5
remote:  !     Requested runtime (Python-3.5) is not available for this stack (heroku-16).
remote:  !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to protected-garden-80811.
remote:
To https://git.heroku.com/"my app name".git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/"my app name".git'
////

According to heroku article, it says 
"Heroku-16 supports the following language runtime versions"
////
~
Python: 2.7, 3.5, 3.6
ref: https://devcenter.heroku.com/articles/heroku-16-stack#runtime-versions-and-installed-packages
////

So, I dont understand why I got this error" Requested runtime (Python-3.5) is not available for this stack (heroku-16)."

**Comment by Udomomo** [comment]
3.5はサポートされてない可能性がありますね。https://devcenter.heroku.com/articles/python-runtimes#supported-python-runtimes

```
Heroku’s Python support extends to the latest stable release from the Python 3.x and Python 2.x series.
Today, this support extends to these specific runtimes:
python-3.6.4
python-2.7.14
```

**Comment by Hoshitter1** [comment]
@Udomomo ご回答ありがとうございます。Today, this support extends to these specific runtimes:python-3.6.4とありますが、3.5はこれに含まれないということでしょうか？3.6.4は3.5より後から出た最新版なので、"3.5もサポートされる"と考えておりました。この認識が間違いということでしょうか。。？

**Comment by Hoshitter1** [comment]
Finally I was able to deploy this app..the first letter of "p"ython in runtime.txt was capital letter but it had to be small letter.
